# Generated by Django 2.0.4 on 2018-04-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('restrictions', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('special_notes', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200)),
                ('curr_capacity', models.IntegerField()),
            ],
        ),
    ]
